Permanent shell scripts: Use PID files; cleanup.

diff --git a/fvwm/scripts/AutoHibernate b/fvwm/scripts/AutoHibernate
--- a/fvwm/scripts/AutoHibernate
+++ b/fvwm/scripts/AutoHibernate
@@ -1,34 +1,31 @@
 #!/usr/bin/env bash
 # FVWM-Crystal helper script that put the omputer in hibernation
 # when the battery is low
-# Usage: Exec exec $[FVWM_SYSTEMDIR]/scripts/AutoHibernate <rate [%]> $[infostore.sysctl]
+# Usage: ExecScript AutoHibernate <rate [%]> $[infostore.sysctl]
 #        launched from components/functions/Exit
 
-#source "${FVWM_SYSTEMDIR}"/scripts/DesktopCheckParent
-
-# be sure no old instance are runninng for the same fvwm parent or with no fvwm parent:
-#PFExec="search_parent_pid"
-#ParentFvwm=$(${PFExec})
-#for i in $(pgrep -f AutoHibernate) ; do
-#	if [[ $$ -ne ${i} ]] ; then
-#		if [[ ${ParentFvwm} -eq $(${PFExec} ${i}) ]] || [[ "nofvwmp" == "$(${PFExec} ${i})" ]] ; then
-#			kill ${i}
-#		fi
-#	fi
-#done
-
+# cleanup can be done after fvwm exits, be sure these vars are setup:
+FVWM_USERDIR="${FVWM_USERDIR}"
+DISPLAY="${DISPLAY}"
+# See ExecScript in components/Standard:
+PIDFile="${FVWM_USERDIR}/tmp/AutoHibernate_${DISPLAY}.pid"
 cleanup() {
-	echo cleanup "$0"
+	rm -f "${PIDFile}"
+	echo "cleanup $$"
 	exit 0
 }
-trap "cleanup" SIGHUP SIGTERM SIGKILL
+trap "cleanup" HUP TERM
 
-if [[ ! "$2" ]]; then
-	cleanup
+# kill old instance
+if [ -f "${PIDFile}" ]; then
+	kill -9 "$(cat "${PIDFile}")" 2>/dev/null
 fi
+# write PID file
+mkdir -p "${FVWM_USERDIR}"/tmp
+echo "$$" > "${PIDFile}"
 
 # write the preference file
-echo "Exec exec ${FVWM_SYSTEMDIR}/scripts/AutoHibernate $1 $2" > "${FVWM_USERDIR}"/preferences/AutoHibernation
+echo "ExecScript AutoHibernate $1 $2" > "${FVWM_USERDIR}"/preferences/AutoHibernation
 
 # check for battery file
 if [ -e /sys/class/power_supply/BAT0/energy_now ]; then
diff --git a/fvwm/scripts/ScreenLidSuspend b/fvwm/scripts/ScreenLidSuspend
--- a/fvwm/scripts/ScreenLidSuspend
+++ b/fvwm/scripts/ScreenLidSuspend
@@ -1,26 +1,25 @@
 #!/usr/bin/env bash
 # On laptop, suspend hybrid from components/functions/Exit
 
-#source "${FVWM_SYSTEMDIR}"/scripts/DesktopCheckParent
-
-# be sure no old instance are runninng for the same fvwm parent or with no fvwm parent:
-# It should work on linux and freebsd
-#PFExec="search_parent_pid"
-#ParentFvwm=$(${PFExec})
-#for i in $(pgrep -f ScreenLidSuspend) ; do
-#	if [[ $$ -ne ${i} ]] ; then
-#		if [[ ${ParentFvwm} -eq $(${PFExec} ${i}) ]] || [[ "nofvwmp" == "$(${PFExec} ${i})" ]] ; then
-#			kill ${i}
-#		fi
-#	fi
-#done
-
-# Be sure it don't attach to init at Quit
+# cleanup can be done after fvwm exits, be sure these vars are setup:
+FVWM_USERDIR="${FVWM_USERDIR}"
+DISPLAY="${DISPLAY}"
+# See ExecScript in components/Standard:
+PIDFile="${FVWM_USERDIR}/tmp/ScreenLidSuspend_${DISPLAY}.pid"
 cleanup() {
-	echo cleanup "$0"
+	rm -f "${PIDFile}"
+	echo "cleanup $$"
 	exit 0
 }
-trap "cleanup" SIGHUP SIGTERM SIGKILL
+trap "cleanup" HUP TERM
+
+# kill old instance
+if [ -f "${PIDFile}" ]; then
+	kill -9 "$(cat "${PIDFile}")" 2>/dev/null
+fi
+# write PID file
+mkdir -p "${FVWM_USERDIR}"/tmp
+echo "$$" > "${PIDFile}"
 
 if [[ $1 == *pm* ]] ; then
 	PMV=pm
@@ -32,11 +31,6 @@ fi
 
 while :
 do
-	# exit if $$ get attached to init at fvwmQuit
-#	if [[ "${ParentFvwm}" != "$(${PFExec} $$)" ]] ; then
-#		cleanup
-#	fi
-
 	sleep 5
 	grep -q closed /proc/acpi/button/lid/*/state
 	if [ $? = 0 ]; then
