cleanup scripts

diff --git a/fvwm/scripts/ScreenLidSuspend b/fvwm/scripts/ScreenLidSuspend
--- a/fvwm/scripts/ScreenLidSuspend
+++ b/fvwm/scripts/ScreenLidSuspend
@@ -1,26 +1,26 @@
 #!/usr/bin/env bash
 # On laptop, suspend hybrid from components/functions/Exit
 
-source "${FVWM_SYSTEMDIR}"/scripts/DesktopCheckParent
+#source "${FVWM_SYSTEMDIR}"/scripts/DesktopCheckParent
 
 # be sure no old instance are runninng for the same fvwm parent or with no fvwm parent:
 # It should work on linux and freebsd
-PFExec="search_parent_pid"
-ParentFvwm=$(${PFExec})
-for i in $(pgrep -f ScreenLidSuspend) ; do
-	if [[ $$ -ne ${i} ]] ; then
-		if [[ ${ParentFvwm} -eq $(${PFExec} ${i}) ]] || [[ "nofvwmp" == "$(${PFExec} ${i})" ]] ; then
-			kill ${i}
-		fi
-	fi
-done
+#PFExec="search_parent_pid"
+#ParentFvwm=$(${PFExec})
+#for i in $(pgrep -f ScreenLidSuspend) ; do
+#	if [[ $$ -ne ${i} ]] ; then
+#		if [[ ${ParentFvwm} -eq $(${PFExec} ${i}) ]] || [[ "nofvwmp" == "$(${PFExec} ${i})" ]] ; then
+#			kill ${i}
+#		fi
+#	fi
+#done
 
 # Be sure it don't attach to init at Quit
 cleanup() {
-	echo cleanup $0
+	echo cleanup "$0"
 	exit 0
 }
-trap cleanup INT QUIT TERM
+trap "cleanup" SIGHUP SIGTERM SIGKILL
 
 if [[ $1 == *pm* ]] ; then
 	PMV=pm
@@ -33,9 +33,9 @@ fi
 while :
 do
 	# exit if $$ get attached to init at fvwmQuit
-	if [[ "${ParentFvwm}" != "$(${PFExec} $$)" ]] ; then
-		cleanup
-	fi
+#	if [[ "${ParentFvwm}" != "$(${PFExec} $$)" ]] ; then
+#		cleanup
+#	fi
 
 	sleep 5
 	grep -q closed /proc/acpi/button/lid/*/state
